#!/usr/bin/env bash
set -euo pipefail

REPO="fajarhide/heimsense"
BINARY="heimsense"
INSTALL_DIR="${HEIMSENSE_INSTALL_DIR:-$HOME/.local/bin}"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { printf "${CYAN}ℹ${NC} %s\n" "$1"; }
ok()    { printf "${GREEN}✓${NC} %s\n" "$1"; }
warn()  { printf "${YELLOW}!${NC} %s\n" "$1"; }
err()   { printf "${RED}✗${NC} %s\n" "$1" >&2; exit 1; }

# --- Detect OS & Arch ---
detect_platform() {
    OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
    ARCH="$(uname -m)"

    case "$OS" in
        darwin) OS="darwin" ;;
        linux)  OS="linux" ;;
        mingw*|msys*|cygwin*|windows_nt) OS="windows" ;;
        *) err "Unsupported OS: $OS" ;;
    esac

    case "$ARCH" in
        x86_64|amd64)        ARCH="amd64" ;;
        aarch64|arm64)       ARCH="arm64" ;;
        *) err "Unsupported arch: $ARCH" ;;
    esac
}

# --- Get latest release version ---
get_latest_version() {
    if command -v gh &>/dev/null; then
        gh api "repos/${REPO}/releases/latest" --jq '.tag_name' 2>/dev/null && return
    fi
    curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null \
        | grep '"tag_name"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/'
}

# --- Download binary ---
download_binary() {
    local version="$1"
    local ext=""
    [ "$OS" = "windows" ] && ext=".exe"
    local filename="${BINARY}-${OS}-${ARCH}${ext}"
    local url="https://github.com/${REPO}/releases/download/${version}/${filename}"

    info "Downloading ${BINARY} ${version} for ${OS}/${ARCH}..."

    mkdir -p "$INSTALL_DIR"
    local dest="${INSTALL_DIR}/${BINARY}"
    [ "$OS" = "windows" ] && dest="${dest}.exe"

    curl -fsSL --progress-bar -o "$dest" "$url"
    chmod +x "$dest"

    ok "Installed to ${dest}"
}

# --- Add to PATH if needed ---
ensure_path() {
    case ":${PATH}:" in
        *":${INSTALL_DIR}:"*) return ;;
    esac

    local shell_rc=""
    if [ -f "$HOME/.zshrc" ]; then
        shell_rc="$HOME/.zshrc"
    elif [ -f "$HOME/.bashrc" ]; then
        shell_rc="$HOME/.bashrc"
    fi

    if [ -n "$shell_rc" ]; then
        echo "" >> "$shell_rc"
        echo "export PATH=\"\$PATH:${INSTALL_DIR}\"" >> "$shell_rc"
        warn "Added ${INSTALL_DIR} to PATH in ${shell_rc}"
        warn "Run 'source ${shell_rc}' or start a new terminal"
    fi

    export PATH="$PATH:${INSTALL_DIR}"
}

# --- Configure Claude Code ---
configure_claude() {
    # Prompt for API key
    printf "\n${BOLD}${CYAN}Claude Code Setup${NC}\n"
    printf "%s" "Enter your LLM provider API key: "
    read -r API_KEY
    [ -z "$API_KEY" ] && { warn "No API key provided, skipping Claude Code setup"; return 1; }

    printf "%s" "Enter provider base URL [https://api.openai.com/v1]: "
    read -r BASE_URL
    BASE_URL="${BASE_URL:-https://api.openai.com/v1}"

    printf "%s" "Enter model name [gpt-5.1]: "
    read -r MODEL
    MODEL="${MODEL:-gpt-5.1}"

    # Write ~/.heimsense/.env so heimsense can start without exports
    local config_dir="$HOME/.heimsense"
    mkdir -p "$config_dir"
    cat > "${config_dir}/.env" <<EOF
# Heimsense config — auto-generated by installer
# Edit this file to change settings: ~/.heimsense/.env
ANTHROPIC_BASE_URL=${BASE_URL}
ANTHROPIC_API_KEY=${API_KEY}
ANTHROPIC_CUSTOM_MODEL_OPTION=${MODEL}
LISTEN_ADDR=:8080
REQUEST_TIMEOUT_MS=120000
MAX_RETRIES=3
EOF
    ok "Config saved to ${config_dir}/.env"

    export ANTHROPIC_API_KEY="$API_KEY"
    export ADAPTER_URL="http://localhost:8080"
    export ANTHROPIC_CUSTOM_MODEL_OPTION="$MODEL"
    export ANTHROPIC_CUSTOM_MODEL_OPTION_NAME="Heimsense Custom Model"
    export ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION="Custom model via Heimsense adapter"

    # Reuse existing setup script
    local script_dir
    script_dir="$(cd "$(dirname "$0")" && pwd)"
    if [ -f "${script_dir}/setup-claude.sh" ]; then
        bash "${script_dir}/setup-claude.sh"
    else
        # Inline minimal setup if setup-claude.sh not available
        local settings="$HOME/.claude/settings.json"
        mkdir -p "$HOME/.claude"
        if [ -f "$settings" ]; then
            cp "$settings" "${settings}.bak"
            python3 -c "
import json, os
with open('$settings') as f:
    data = json.load(f)
data.setdefault('env', {})
data['env']['ANTHROPIC_BASE_URL'] = 'http://localhost:8080'
data['env']['ANTHROPIC_CUSTOM_MODEL_OPTION'] = os.environ.get('ANTHROPIC_CUSTOM_MODEL_OPTION', 'gpt-5.1')
data['env']['ANTHROPIC_CUSTOM_MODEL_OPTION_NAME'] = os.environ.get('ANTHROPIC_CUSTOM_MODEL_OPTION_NAME', 'Heimsense Custom Model')
data['env']['ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION'] = os.environ.get('ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION', 'Custom model via Heimsense adapter')
data['env']['ANTHROPIC_AUTH_TOKEN'] = os.environ.get('ANTHROPIC_API_KEY', '')
data['env']['CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC'] = '1'
with open('$settings', 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
"
        else
            cat > "$settings" <<EOF
{
  "\$schema": "https://json.schemastore.org/claude-code-settings.json",
  "env": {
    "ANTHROPIC_BASE_URL": "http://localhost:8080",
    "ANTHROPIC_CUSTOM_MODEL_OPTION": "${MODEL}",
    "ANTHROPIC_CUSTOM_MODEL_OPTION_NAME": "Heimsense Custom Model",
    "ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION": "Custom model via Heimsense adapter",
    "ANTHROPIC_AUTH_TOKEN": "${API_KEY}",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1"
  }
}
EOF
        fi

        # Bypass onboarding
        local claude_json="$HOME/.claude.json"
        if [ -f "$claude_json" ]; then
            python3 -c "
import json
with open('$claude_json') as f:
    data = json.load(f)
data['hasCompletedOnboarding'] = True
with open('$claude_json', 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
"
        fi
    fi

    ok "Claude Code configured!"
    return 0
}

# --- Main ---
main() {
    printf "\n${BOLD}${CYAN}heim·sense${NC} — Install & Setup\n\n"

    detect_platform
    info "Platform: ${OS}/${ARCH}"

    VERSION="$(get_latest_version)"
    [ -z "$VERSION" ] && err "Could not determine latest version"
    info "Latest version: ${VERSION}"

    download_binary "$VERSION"
    ensure_path

    # Configure Claude Code
    if configure_claude; then
        printf "\n${GREEN}${BOLD}All set!${NC}\n\n"
        printf "  1. Start Heimsense:\n"
        printf "     ${CYAN}heimsense${NC}\n\n"
        printf "  2. In another terminal, run:\n"
        printf "     ${CYAN}claude${NC}\n\n"
        printf "  3. Inside Claude, run ${CYAN}/model${NC} and select Heimsense Custom Model\n\n"
        printf "  Edit config anytime: ${CYAN}~/.heimsense/.env${NC}\n"
    else
        printf "\n${GREEN}${BOLD}Binary installed!${NC}\n\n"
        printf "  Start with: ${CYAN}heimsense${NC}\n"
        printf "  Then configure Claude manually or run: ${CYAN}make setup${NC}\n"
    fi
}

main "$@"
